### ISSUE TITLE
Add organization to RepositoryTable spec

### ISSUE THREAD

**Issue by harunsmrkovic** [rubenmarcus/repo-search-github#2]
What do you think about re-organizing the test structure so that the assertions are wrapped in a single describe?

Also, I would suggest using either `it` or `test` consistently throughout the codebase.

https://github.com/rubenmarcus/repo-search-github/blob/c8039b1d730da3d7f8adea843ead6cf697a133f6/src/tests/RepositoryTable.spec.tsx#L23-L28

**Comment by rubenmarcus** [comment]
[done](https://github.com/rubenmarcus/repo-search-github/commit/3b8c498baaa303a80b51f5cc7175992b7a6de413)

thanks for the review!
