### ISSUE TITLE
De-couple navigation logic from data fetching logic

### ISSUE THREAD

**Issue by harunsmrkovic** [rubenmarcus/repo-search-github#3]
Hey, this logic for synchronizing the URL with the user navigation seems a bit out of place in the hook used for fetching the data from the API.

What do you think about separating these concerns? I am thinking that this would best fit into the page/container component.

https://github.com/rubenmarcus/repo-search-github/blob/c8039b1d730da3d7f8adea843ead6cf697a133f6/src/hooks/useReposData.ts#L26-L30

**Comment by rubenmarcus** [comment]
[done](https://github.com/rubenmarcus/repo-search-github/commit/3b8c498baaa303a80b51f5cc7175992b7a6de413)
